### ISSUE TITLE
Request load qml pages

### ISSUE THREAD

**Issue by mmjvox** [lirios/browser#92]
Can this browser load qml pages like html pages?
It would be great if browsers also supported qml.

**Comment by timsueberkrueb** [comment]
In theory, yes, but it would not be secure, at least not with feasible investment.
Browser engines are designed to run untrusted code, the QML engine is not.
Loading local (trusted) QML files might be okay for testing purposes but then one can just use `qmlscene` to achieve the same thing.
Qt [supports WebAssembly](https://doc.qt.io/qt-5/wasm.html) so that's probably the way to go if you want to use QML applications in a web browser.

**Comment by mmjvox** [comment]
minimum output size of qt webassembly for qml is about 20 MB
